name: Update Check

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */1 * * *' # Hourly

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x
          check-latest: true

      - name: Install Dependencies
        run: npm install
        env:
          CI: true

      - name: Check for Updates
        id: check_for_updates
        run: echo ::set-output name=icon_changes::$(npm start --silent)echo "::set-output name=changes::$()"
        env:
          CI: true

      - name: Output
        run: echo ${{ steps.check_for_updates.outputs.icon_changes }} > a.out
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: 'chore(icons): Sync Icons'
          title: Icon Changes
          body: |
            # Icon Changes

            ${{ steps.check_for_updates.outputs.icon_changes }}
          branch: icon-updates
