name: Update Check

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'ignore'
        required: false
  schedule:
    - cron: '0 */1 * * *' # Hourly

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: npm install
        env:
          CI: true

      - name: Check for Updates
        id: check_for_updates
        run: |
          changes=$(npm start --silent)
          changes="${changes//'%'/'%25'}"
          changes="${changes//$'\n'/'%0A'}"
          changes="${changes//$'\r'/'%0D'}"
          # echo $changes
          echo "::set-output name=icon_changes::$changes"
        env:
          CI: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'chore(icons): Sync Icons'
          title: Icon Changes
          body: |
            # Icon Changes

            ${{ steps.check_for_updates.outputs.icon_changes }}
          branch: icon-updates
          assignees: |
            stramel
